package com.yqwl.datamiddle.realtime.bean;

import lombok.Data;


import java.sql.Timestamp;


@Data
public class Sptb01C {
    private  int IDNUM;
    private String cpcdbh;
    private Long ddjrq;
    private String vczydm;
    private String vwlckdm;
    private String czt;
    private String czldbh;
    private String vbz;
    private String cyslx;
    private String cpcdydlx;
    private String vdwdm;
    private String vscdz;
    private String cdhddm;
    private String cfydd;
    private String cly;
    private String vysfs;
    private String cdydbh;
    private String cjhdh;
    private String cjhlx;
    private String cssgs;
    private Long dxdsj;
    private Long dysjssj;
    private String cdydbh1;
    private String cddy;
    private Long ddrsj;
    private String cdkhdm;
    private String ccysdm;
    private String cgs;
    private String cspgdm;
    private String cspgnm;
    private String ca2Jhbs;
    private String vfczt;
    private String vsczt;
    private String vph;
    private String cqwh;
    private String vsqmc;
    private String vsxmc;
    private String vqygs;
    private String czjgsdm;
    private String vyscdm;
    private Long nlc;
    private String cxldm;
    private String vqygsYf;
    private String cyssdmYf;
    private String vqygsYf1;
    private String cyssdmYf1;
    private Long dzyrq;
    private Long dstamp;
    private String cyssdmSj;
    private String cxldmJfcc;
    private String cxldmJfcd;
    private String cxldmJfqd;
    private String cxsgsdm;
    private String vxsgsmc;
    private String cydlxmc;
    private String vcysdm;
    private String qycx;
    private Long dppsjJf;
    private String cyslxms;
    private Integer ndj;
    private Integer nZdxh;
    private String evFlag;
    private String svFlag;
    private String interCode;
    private String nameFrom;
    private String nameTo;
    private String senPerson;
    private String recPerson;
    private String personPhone;
    private String addressFrom;
    private String addressTo;
    private Long reqDate;
    private Long fhDate;
    private String submi;
    private String deptm;
    private String info;
    private String cartype;
    private String brand;
    private String name2;
    private String cydlx;
    private String cbsFyzy;
    private Long dzyfprq;
    private Long dzyyfrq;
    private String cyssdmYfFy;
    private String cpbbs;
    private String svType;
    private String vzylxJf;
    private Timestamp createTime;
    private Timestamp updateTime;

}
