server:
#  port: 8090 定时任务不需要端口
  tomcat:
    max-swallow-size: -1
  error:
    include-exception: true
    include-stacktrace: ALWAYS
    include-message: ALWAYS
  servlet:
    context-path: /jeecg-boot
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*

# spring.main.web-application-type=none
spring:
  main:
    web-application-type: none

  #json 时间戳统一转换
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
  jpa:
    open-in-view: false
  activiti:
    check-process-definitions: false
    #启用作业执行器
    async-executor-activate: false
    #启用异步执行器
    job-executor-activate: false
  aop:
    proxy-target-class: true

  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    druid:
      stat-view-servlet:
        enabled: false
        loginUsername: admin
        loginPassword: 123456
        allow:
      web-stat-filter:
        enabled: true
    dynamic:
      druid: # 全局druid参数，绝大部分值和默认保持一致。(现已支持的参数如下,不清楚含义不要乱设置)
        # 连接池的配置信息
        # 初始化大小，最小，最大
        initial-size: 5
        min-idle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        # 介于当前数据源新增Oracle,当前validationQuery的语句无法适用所有,故改为单独数据源单独设置
        # validationQuery: SELECT 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,slf4j
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      datasource:
        master:
          url: jdbc:mysql://192.168.3.4:3306/data_middle?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: fengqiwulian
          password: fengqiwulian
          driver-class-name: com.mysql.cj.jdbc.Driver
          druid:
            validationQuery: SELECT 1
        oracle-vts:
          url: jdbc:oracle:thin:@192.168.3.95:1521:orcl
          username: flinkuser
          password: flinkpw
          #username: AIOT_VTS_DEV
          #password: 123
          driver-class-name: oracle.jdbc.OracleDriver
          druid:
            validationQuery: SELECT 1 FROM DUAL
#        # 多数据源配置
#        slave_0:
#          url: jdbc:clickhouse://192.168.3.95:8123/default
#          username:
#          password:
#          driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
#          initialSize: 10
#          maxActive: 100
#          minIdle: 10
#          maxWait: 6000
#          druid:
#            validationQuery: SELECT 1
#        slave_1:
#          url: jdbc:clickhouse://192.168.3.96:8123/default
#          username:
#          password:
#          driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
#          initialSize: 10
#          maxActive: 100
#          minIdle: 10
#          maxWait: 6000
#          druid:
#            validationQuery: SELECT 1
#        slave_2:
#          url: jdbc:clickhouse://192.168.3.97:8123/default
#          username:
#          password:
#          driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
#          initialSize: 10
#          maxActive: 100
#          minIdle: 10
#          maxWait: 6000
#          druid:
#            validationQuery: SELECT 1
        wareHouse:
            url: jdbc:mysql://192.168.3.4:3306/data_middle_flink?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
            username: fengqiwulian
            password: fengqiwulian
            driver-class-name: com.mysql.cj.jdbc.Driver
            druid:
              validationQuery: SELECT 1

#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:org/jeecg/modules/**/xml/*Mapper.xml,classpath*:org/jeecg/yqwl/datamiddle/ads/order/**/xml/**Mapper.xml,classpath*:org/jeecg/yqwl/datamiddle/job/mapper/xml/**.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
